# Generated by Django 4.0.3 on 2022-03-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_members_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoListe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chore', models.CharField(max_length=200)),
            ],
        ),
    ]
